// Lightweight DOM Injector for System Modals with Japanese Labels
(function injectModals() {
  const container = document.createElement('div');
  container.id = 'dynamicModalContainer';
  container.innerHTML = [
    '<div id="qrModal" class="modal-overlay"><div class="cyber-modal" style="max-width:520px;text-align:center;"><div class="modal-header"><div class="modal-title"><i class="fas fa-qrcode" style="color:var(--amber-warning)"></i> QR Code ลงทะเบียน / 抽選登録 QR Code</div><button class="close-btn">&times;</button></div><div class="modal-body" style="display:flex;flex-direction:column;align-items:center;gap:20px"><p>สแกนเพื่อกรอกข้อมูล / スキャンして登録 <strong>ชื่อ / 氏名 / บริษัท / 会社名</strong></p><div id="qrcodeBox" style="background:#fff;padding:18px;border-radius:12px"></div><input type="text" id="qrRegUrlInput" class="cyber-input" readonly style="text-align:center;font-size:0.85rem"><div style="display:flex;gap:10px"><button class="cyber-btn" id="copyUrlBtn"><i class="fas fa-copy"></i> คัดลอกลิงก์ / コピー</button><a href="register.html" target="_blank" class="cyber-btn" style="text-decoration:none"><i class="fas fa-external-link-alt"></i> เปิดหน้าลงทะเบียน / 開く</a></div></div></div></div>',
    '<div id="prizeModal" class="modal-overlay"><div class="cyber-modal" style="max-width:800px"><div class="modal-header"><div class="modal-title"><i class="fas fa-gifts" style="color:var(--green-active)"></i> จัดการของรางวัล / 賞品管理</div><button class="close-btn">&times;</button></div><div class="modal-body"><form id="addPrizeForm" style="display:flex;flex-direction:column;gap:15px;background:rgba(0,243,255,0.03);padding:20px;border-radius:10px;border:1px solid var(--border-cyan)"><h4 style="color:var(--cyan-primary)">+ เพิ่มของรางวัลใหม่ / 賞品追加</h4><div style="display:flex;gap:15px;flex-wrap:wrap"><input type="text" id="newPrizeName" class="cyber-input" placeholder="ชื่อของรางวัล / 賞品名" required style="flex:2"><input type="number" id="newPrizeCount" class="cyber-input" placeholder="จำนวน / 数量" min="1" value="1" required style="flex:1"><input type="number" id="newPrizeBatch" class="cyber-input" placeholder="สุ่มรอบละ / 回" min="1" value="1" required style="flex:1"></div><div style="display:flex;gap:15px;align-items:center"><input type="file" id="newPrizeImgFile" accept="image/*" class="cyber-input" style="flex:1"><span style="color:var(--text-muted);font-size:0.85rem">หรือวางลิงก์รูป / URL:</span><input type="url" id="newPrizeImgUrl" class="cyber-input" placeholder="https://..." style="flex:1"></div><button type="submit" class="cyber-btn" style="align-self:flex-end"><i class="fas fa-plus"></i> เพิ่มของรางวัล / 追加</button></form><div style="display:flex;justify-content:space-between;align-items:center;margin-top:25px"><h4 style="color:var(--amber-warning)">รายการของรางวัลทั้งหมด / 賞品一覧</h4><button id="clearAllPrizesBtn" class="cyber-btn danger"><i class="fas fa-trash-alt"></i> ลบของรางวัลทั้งหมด / 全削除</button></div><div id="prizeListGrid" class="prize-list-grid"></div></div></div></div>',
    '<div id="winnerModal" class="modal-overlay"><div class="cyber-modal"><div class="modal-header"><div class="modal-title"><i class="fas fa-trophy" style="color:var(--amber-warning)"></i> ยินดีด้วยกับผู้โชคดี! / おめでとうございます！</div><button class="close-btn">&times;</button></div><div class="modal-body"><div class="winner-stage-banner"><img id="winnerPrizeImg" class="winner-prize-img" src="" alt="Prize"><div class="winner-prize-title" id="winnerPrizeTitle">รางวัลใหญ่ GRAND PRIZE</div><div class="winner-subtitle">CANON LUCKY WINNERS</div></div><div id="winnerRevealGrid" class="winner-grid"></div></div></div></div>',
    '<div id="manageModal" class="modal-overlay"><div class="cyber-modal" style="max-width:900px"><div class="modal-header"><div class="modal-title"><i class="fas fa-users-cog"></i> จัดการรายชื่อผู้เข้าร่วมงาน / 参加者管理</div><button class="close-btn">&times;</button></div><div class="modal-body"><div style="display:flex;flex-direction:column;gap:15px;margin-bottom:20px;background:rgba(0,243,255,0.03);padding:18px;border-radius:10px;border:1px solid var(--border-cyan)"><div style="display:flex;justify-content:space-between;align-items:center"><h4 style="color:var(--cyan-primary)"><i class="fas fa-paste"></i> วางรายชื่อ (Copy-Paste) / 貼り付け または CSV</h4><button id="clearAllParticipantsBtn" class="cyber-btn danger" style="padding:6px 16px;font-size:0.8rem"><i class="fas fa-trash-alt"></i> ลบรายชื่อทั้งหมด / 全削除</button></div><textarea id="pastedNamesInput" class="cyber-input" style="height:90px;resize:vertical;font-size:0.95rem;line-height:1.4" placeholder="วางรายชื่อที่นี่ (1 ชื่อต่อ 1 บรรทัด / 1行に1名):&#10;นายสมชาย ใจดี, บริษัท แคนนอน&#10;山田 太郎, Canon Inc."></textarea><div style="display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap"><button id="importPastedBtn" class="cyber-btn" style="background:rgba(0,255,136,0.15);border-color:var(--green-active);color:var(--green-active)"><i class="fas fa-file-import"></i> นำเข้ารายชื่อที่วางไว้ / インポート</button><div style="display:flex;align-items:center;gap:10px"><span style="font-size:0.85rem;color:var(--text-muted)">หรือลากไฟล์ CSV:</span><input type="file" id="csvFileInput" accept=".csv, .txt" class="cyber-input" style="font-size:0.8rem;padding:6px 12px;width:auto"></div></div></div><div class="table-container"><table class="cyber-table"><thead><tr><th>#</th><th>รหัส / ID</th><th>ชื่อ-นามสกุล / 氏名</th><th>แผนก/บริษัท / 所属</th><th>สถานะ / ステータス</th><th style="text-align:center">จัดการ</th></tr></thead><tbody id="participantTableBody"></tbody></table></div></div></div></div>',
    '<div id="historyModal" class="modal-overlay"><div class="cyber-modal"><div class="modal-header"><div class="modal-title"><i class="fas fa-history"></i> รายชื่อผู้ได้รับรางวัลทั้งหมด / 当選履歴一覧</div><button class="close-btn">&times;</button></div><div class="modal-body"><div class="table-container"><table class="cyber-table"><thead><tr><th>ลำดับ</th><th>รหัส / ID</th><th>ชื่อ-นามสกุล / 氏名</th><th>แผนก/บริษัท / 所属</th><th>รางวัลที่ได้รับ / 賞品</th><th>เวลา / 時間</th></tr></thead><tbody id="winnerHistoryTableBody"></tbody></table></div><div class="actions-row"><button id="resetWinnersBtn" class="cyber-btn danger"><i class="fas fa-rotate-right"></i> รีเซ็ตสิทธิ์ผู้โชคดีทั้งหมด / リセット</button><button id="exportCsvBtn" class="cyber-btn"><i class="fas fa-download"></i> ดาวน์โหลดผลรางวัล (CSV) / CSV出力</button></div></div></div></div>'
  ].join('');
  document.body.appendChild(container);
})();
